imports:
    - { resource: config.yml }
    - { resource: parameters_prod.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

swiftmailer:
    default_mailer: real_mailer
    mailers:
        real_mailer:
            transport:            '%mailer_transport%'
            username:             '%mailer_user%'
            password:             '%mailer_password%'
            host:                 '%mailer_host%'
            port:                 587
            #encryption:           ssl
        spool_mailer:
            transport:            '%mailer_transport%'
            username:             '%mailer_user%'
            password:             '%mailer_password%'
            host:                 '%mailer_host%'
            port:                 587
            #encryption:           ssl
            spool:
                type:             file
                path:             '%kernel.cache_dir%/swiftmailer/spool'

