parameters:
    #MAILER
    mailer_transport: smtp
    mailer_user:      nadawca@noclegniepolomice.pl
    mailer_password:  ~
    mailer_host:      s95.linuxpl.com

    mailer_from_mail: nadawca@noclegniepolomice.pl
    mailer_from_name: NoclegNiepolomice.pl

    #contact form
    contact_form_mail: nadawca@noclegniepolomice.pl

    #DB
    database_host: localhost
    database_port: null
    database_name: ~
    database_user: ~
    database_password: ~

    #-------------------------------------------------------------------------------------------------------------------
    #facebook login
    facebook_client_id: 123
    facebook_client_secret: 123
    #google login
    google_client_id: 123
    google_client_secret: 13
    #google maps
    google_maps_api_key: ~