parameters:
    #MAILER
    mailer_transport: smtp
    mailer_user:      nadawca@noclegniepolomice.pl
    mailer_password:  ~
    mailer_host:      s95.linuxpl.com

    mailer_from_mail: nadawca@noclegniepolomice.pl
    mailer_from_name: NoclegNiepolomice.pl

    #contact form
    contact_form_mail: lemmyafiver@gmail.com

    #DB
    database_host: localhost
    database_port: null
    database_name: noclegniepolomice
    database_user: ~
    database_password: ~

    #facebook login
    facebook_client_id: ~
    facebook_client_secret: ~

    #google login
    google_client_id: ~
    google_client_secret: ~

    #google maps
    google_maps_api_key: ~