# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    #CmsArticleType form
    form.cms_article_type:
        class: AdminBundle\Form\CmsArticleType
        arguments: ['@app.language_helper']
        tags:
            - { name: form.type }

    #CmsStaticPage form
    form.cms_static_page:
        class: AdminBundle\Form\CmsStaticPageType
        arguments: ['@app.language_helper']
        tags:
            - { name: form.type }

    form.cms_page:
        class: AdminBundle\Form\CmsPageType
        arguments: ['@app.language_helper']
        tags:
            - { name: form.type }

    #CmsGallery form
    form.cms_gallery_page:
        class: AdminBundle\Form\CmsGalleryType
        arguments: ['@app.language_helper']
        tags:
            - { name: form.type }

    form.cms_config:
        class: AdminBundle\Form\CmsConfigForm
        arguments: ['@app.language_helper']
        tags:
            - { name: form.type }

