# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
      #APP-----------
      app.tester:
          class: AppBundle\Utils\TesterService
          arguments: ['@doctrine.orm.entity_manager']

      #set locale for session
      app.locale_listener:
          class: AdminBundle\EventListener\LocaleListener
          arguments: ['%kernel.default_locale%']
          tags:
              - { name: kernel.event_subscriber }

      app.security_helper:
          class: AppBundle\Utils\SecurityHelper

      app.string_helper:
          class: AppBundle\Utils\StringHelper
          arguments: ['@filesystem']

      app.file_uploader:
          class: AppBundle\Utils\FileUploader
          arguments: ['@app.string_helper']

      app.filesystem_helper:
          class: AppBundle\Utils\FilesystemHelper
          arguments: ['@filesystem']

      app.language_helper:
          class: AppBundle\Utils\LanguageHelper
          arguments: ['@doctrine.orm.entity_manager']

      app.config_helper:
         class: AppBundle\Utils\ConfigHelper
         arguments: ['@doctrine.orm.entity_manager']

      app.test_subscriber:
          class: AppBundle\EventListener\TestSubscriber
          #tags:
              #- {name: 'kernel.event_subscriber'}
      #Handlers
      app.authentication_handler:
          class: AppBundle\Handlers\AuthenticationHandler

      #HWIOAuth user provider
      hwioauth.my_user_provider:
          class: HWI\Bundle\OAuthBundle\Security\Core\User\MyOAuthUserProvider
          arguments: ['@doctrine.orm.entity_manager']

      twig.extension.text:
          class: Twig_Extensions_Extension_Text
          tags:
              - { name: twig.extension }