<?php

namespace AdminBundle\Repository;

/**
 * CmsArticleTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsArticleTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
