<?php

namespace AdminBundle\Repository;
use Doctrine\ORM\EntityNotFoundException;

/**
 * CmsArticleFileRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsArticleFileRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @param $uploadDir
     */
    public function remove($id, $uploadDir) {
        $em = $this->getEntityManager();
        $cmsArticleFileEntity = $em->find('AdminBundle:CmsArticleFile', $id);
        if (!$cmsArticleFileEntity) {
            throw new EntityNotFoundException();
        }
        //var_dump($uploadDir .'/'. $cmsStaticPageImageObj->getFileName());
        $filePath = $uploadDir . $cmsArticleFileEntity->getFileName();
        if (file_exists($filePath)) {
            if (unlink($filePath)) {
                $em->remove($cmsArticleFileEntity);
                $em->flush();
                return true;
            }
            throw new \Exception();
        }
        throw new \Exception();
    }

}
