<?php

namespace AdminBundle\Repository;

/**
 * CmsArticleCategoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsArticleCategoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
