<?php

namespace AdminBundle\Repository;

/**
 * CmsCategoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsCategoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
