<?php

namespace AdminBundle\Repository;
use AdminBundle\Entity\CmsConfig;

/**
 * CmsConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsConfigRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Get config value by key
     * @param $configKey
     * @return string
     */
    public function getValueByKey($configKey) {
        /** @var CmsConfig $cmsConfig */
        $cmsConfig =  $this->findOneBy(['configKey' => $configKey]);
        if (!$cmsConfig) {
            return $configKey;
        }
        if ($cmsConfig->getIsTranslatable()) {
            return $cmsConfig->getConfigDescription();
        }
        if ($cmsConfig->getIsHasImage()) {
            return $cmsConfig->getImage();
        }
        return $cmsConfig->getConfigValue();
    }


    /**
     * Get config value by key
     * @param $configKey
     * @return string
     */
    public function getByKey($configKey) {
        /** @var CmsConfig $cmsConfig */
        $cmsConfig =  $this->findOneBy(['configKey' => $configKey]);
        if (!$cmsConfig) {
            return null;
        }
        return $cmsConfig;
    }



}
