<?php

namespace AdminBundle\Repository;

/**
 * CmsConfigTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsConfigTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
