<?php

namespace AdminBundle\Repository;

/**
 * CmsGalleryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsGalleryCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
