<?php

namespace AdminBundle\Repository;

/**
 * CmsGalleryCategoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsGalleryCategoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
