<?php

namespace AdminBundle\Repository;

/**
 * CmsGalleryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsGalleryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
