<?php

namespace AdminBundle\Repository;

/**
 * CmsLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsLanguageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get codes of active languages
     * @return array
     */
    public function getActiveCodes() {
        $result =  $this->getEntityManager()
            ->createQuery(
                'SELECT l.code FROM AdminBundle:CmsLanguage l WHERE l.isActive = 1'
            )
            ->getScalarResult();
        return array_map('current', $result);
    }

    /**
     * @return array
     */
    public function getActivePageLanguages() {
        $qb = $this->createQueryBuilder('lang')
            ->where('lang.isActiveOnPage = 1')
            ->orderBy('lang.id', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }


    
    
}
