<?php

namespace AdminBundle\Repository;

/**
 * CmsMessageBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsMessageBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
