<?php

namespace AdminBundle\Repository;

/**
 * CmsPageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
