<?php

namespace AdminBundle\Repository;
use AdminBundle\Entity\CmsPage;

/**
 * CmsPageFileRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPageFileRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get gallery images
     * @param string $type
     * @return array
     */
    public function getFilesByCmsPage(CmsPage $cmsPage) {
        $qb = $this->createQueryBuilder('file')
            ->where('file.cmsPage = :cmsPage')
                ->setParameter(':cmsPage', $cmsPage)
            ->andWhere('file.type = :type')
                ->setParameter(':type', 'img')
            ->orderBy('file.sort', 'ASC')
            ->addOrderBy('file.id', 'DESC')
            ->getQuery();
        return $qb->getResult();
    }

}
