<?php

namespace AdminBundle\Repository;
use AdminBundle\Entity\CmsCategory;

/**
 * CmsPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get page by slug
     */
    public function getOneBySlug($slug) {
        $qb = $this->createQueryBuilder('p')
            ->join('p.translations', 'trans')
            ->where('trans.slug = :slug')
            ->setParameter(':slug', $slug)
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    public function getPagesByCategory(CmsCategory $cmsCategory) {
        $qb = $this->createQueryBuilder('p')
            ->where('p.cmsCategory = :cmsCategory')
            ->setParameter(':cmsCategory', $cmsCategory)
            ->orderBy('p.sort', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }


    /**
     * Get max sort value
     * @return mixed
     */
    public function getMaxSort(CmsCategory $cmsCategory) {
        $qb = $this->createQueryBuilder('r')
            ->select('MAX(r.sort) AS max_sort')
            ->where('r.cmsCategory = :cmsCategory')
            ->setParameter(':cmsCategory', $cmsCategory)
        ;
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    
}
