<?php

namespace AdminBundle\Repository;

/**
 * CmsStaticPageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsStaticPageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
