<?php

namespace AdminBundle\Repository;

/**
 * CmsStaticPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsStaticPageRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function save($object, $persist = true) {
        if ($persist) {
            $this->getEntityManager()->persist($object);
        }
        $this->getEntityManager()->flush();
    }


    /**
     * @param $slug
     */
    public function getBySlug($slug) {
        $qb = $this->createQueryBuilder('page')
            ->join('page.translations', 'trans')
            ->where('trans.slug = :slug')
            ->setParameter(':slug', $slug);
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    /**
     * Get record by param
     * @param $param
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByParam($param) {
        $qb = $this->createQueryBuilder('page')
            ->where('page.param = :param')
            ->setParameter(':param', $param);
        return $qb->getQuery()->getOneOrNullResult();
    }


    /**
     * Get all pages indexed by param
     * @return array
     */
    public function getAll() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AdminBundle:CmsStaticPage p INDEX BY p.param'
            )
            ->getResult();
    }
    
    
    


}
