<?php

namespace AdminBundle\Repository;

/**
 * CmsTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
