<?php

namespace AdminBundle\Repository;

/**
 * CmsTranslationTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsTranslationTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
