<?php

namespace AdminBundle\Repository;

/**
 * CmsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsUserRepository extends \Doctrine\ORM\EntityRepository
{
}
