<?php

namespace AdminBundle\Repository;
use AdminBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get all users
     * @param bool $returnQuery
     * @return array|\Doctrine\ORM\Query
     */
    public function getAll($returnQuery = false) {
        $qb = $this->createQueryBuilder('u')
            ->where('IDENTITY(u.userGroup) != :user_group_admin')
            ->setParameter(':user_group_admin', 1)
            ->orderBy('u.id', 'DESC')
            ->getQuery();
        if ($returnQuery) {
            return $qb;
        }
        return $qb->getResult();
    }


    /**
     * @param $socialId
     */
    public function findOneBySocialId($socialId) {
        $qb = $this->createQueryBuilder('u')
            ->where('u.facebookID = :socialID')
            ->orWhere('u.googleID = :socialID')
            ->setParameter(':socialID', $socialId);
        return $qb->getQuery()->getFirstResult();
    } 
    

    public function save($object, $persist = true) {
        if ($persist) {
            $this->getEntityManager()->persist($object);
        }
        $this->getEntityManager()->flush();
        return $object;
    }



}
