<?php

namespace AdminBundle\Repository;

/**
 * WineColorTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineColorTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
