<?php

namespace AdminBundle\Repository;

/**
 * WineMaturityTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineMaturityTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
