<?php

namespace AdminBundle\Repository;

/**
 * WineCountryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineCountryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
