<?php

namespace AdminBundle\Repository;

/**
 * WineCountryRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineCountryRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
