<?php

namespace AdminBundle\Repository;

/**
 * WineTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
