<?php

namespace AdminBundle\Repository;

/**
 * WineCountryRegionTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineCountryRegionTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
