<?php

namespace AdminBundle\Repository;

/**
 * WineColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineColorRepository extends \Doctrine\ORM\EntityRepository
{
}
