<?php

namespace AdminBundle\Repository;

/**
 * WineMaturityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineMaturityRepository extends \Doctrine\ORM\EntityRepository
{
}
