<?php

namespace AdminBundle\Repository;

/**
 * WineCountrySubregionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineCountrySubregionRepository extends \Doctrine\ORM\EntityRepository
{
}
