<?php

namespace RsBundle\Repository;

/**
 * RsConfigTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsConfigTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
