<?php

namespace RsBundle\Repository;

/**
 * RsFacilityItemTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsFacilityItemTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
