<?php

namespace RsBundle\Repository;

/**
 * RsMealTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsMealTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
