<?php

namespace RsBundle\Repository;

/**
 * RsMealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsMealRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function save($object, $persist = true) {
        if ($persist) {
            $this->getEntityManager()->persist($object);
        }
        $this->getEntityManager()->flush();
    }

}
