<?php

namespace RsBundle\Repository;

/**
 * RsPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsPackageRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get max sort value
     * @return mixed
     */
    public function getMaxSort() {
        $qb = $this->createQueryBuilder('r')
            ->select('MAX(r.sort) AS max_sort');
        return $qb->getQuery()->getSingleScalarResult();
    }


    /**
     * Get Active Packages
     */
    public function getActive() {
        $qb = $this->createQueryBuilder('p')
            ->where('p.isActive = 1')
            ->orderBy('p.sort', 'ASC')
            ->addOrderBy('p.id', 'DESC')
            ->getQuery();
        return $qb->getResult();
    }


    /**
     * @param $slug
     */
    public function getBySlug($slug) {
        $qb = $this->createQueryBuilder('package')
            ->join('package.translations', 'trans')
            ->where('trans.slug = :slug')
            ->setParameter(':slug', $slug);
        return $qb->getQuery()->getOneOrNullResult();
    }


}
