<?php

namespace RsBundle\Repository;

/**
 * RsPackageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsPackageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
