<?php

namespace RsBundle\Repository;

/**
 * RsRoomTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsRoomTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
