<?php

namespace RsBundle\Repository;
use RsBundle\Entity\RsRoom;

/**
 * RsRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsRoomRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param RsRoom $rsRoom
     * @return array
     */
    public function getByBaseRoom(RsRoom $rsRoom) {
        return $this->findBy(['baseRoom' => $rsRoom]);
    }


    /**
     * Get max sort value
     * @return mixed
     */
    public function getMaxSort() {
        $qb = $this->createQueryBuilder('r')
            ->select('MAX(r.sort) AS max_sort');
        return $qb->getQuery()->getSingleScalarResult();
    }


    /**
     * Get Active rooms 
     * @return array
     */
    public function getActive() {
        $query = $this->createQueryBuilder('room')
            ->where('room.isActive = true')
            ->orderBy('room.sort', 'ASC')
            ->getQuery();
        return $query->getResult();
    }



    /**
     * @param $slug
     */
    public function getBySlug($slug) {
        $qb = $this->createQueryBuilder('room')
            ->join('room.translations', 'trans')
            ->where('trans.slug = :slug')
            ->setParameter(':slug', $slug);
        return $qb->getQuery()->getOneOrNullResult();
    }
    

    public function save($object, $persist = true) {
        if ($persist) {
            $this->getEntityManager()->persist($object);
        }
        $this->getEntityManager()->flush();
    }
    
    
}
