<?php

namespace RsBundle\Repository;

/**
 * RsRoomAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsRoomAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
